# Generated by Django 5.2.1 on 2025-06-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(blank=True, choices=[('sent', 'Sent'), ('failed', 'Failed'), ('queued', 'Queued')], max_length=20, null=True),
        ),
    ]
