# Generated by Django 5.2.1 on 2025-06-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuesuggestion',
            name='rental_cost',
        ),
    ]
