# Generated by Django 5.2.1 on 2025-06-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_registration_email_remove_registration_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='qr_code_url',
            new_name='edit_url',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='form_data',
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_url',
            field=models.URLField(blank=True),
        ),
    ]
