# Generated by Django 5.2.1 on 2025-06-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='modified_by',
        ),
    ]
