# Generated by Django 5.2.1 on 2025-06-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_emaillog_tone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='scheduled_time',
        ),
    ]
