# Generated by Django 5.2.1 on 2025-05-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
