# Generated by Django 5.2.1 on 2025-06-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_socialpost_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='event_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='form_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='form_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
