# Generated by Django 5.2.1 on 2025-06-06 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_eventeditor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardOfTheDay',
        ),
    ]
