# Generated by Django 5.2.1 on 2025-06-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_registration_event_intro_registration_form_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='edit_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
