# Generated by Django 5.2.1 on 2025-06-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_registration_edit_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='edit_url',
        ),
    ]
